### ISSUE TITLE
Completion error occurs.

### ISSUE THREAD

**Issue by unikuragit** [lighttiger2505/sqls#11]
It is used in Windows + gVim + vim-lsp + PostgreSQL.
sqls is the latest version.

The environment is as follows.
> Windows10 64bit 1909
> VIM - Vi IMproved 8.2 MS-Windows 64-bit GUI version Included patches: 1-735
> go version go1.13.6 windows/amd64
> PostgreSQL 12.2, compiled by Visual C++ build 1914, 64-bit

The following is the error log of vim-lsp.
> panic serving textDocument/completion:
> runtime error: invalid memory address or nil pointer dereference
> goroutine 18 [running]:
> github.com/lighttiger2505/sqls/internal/handler.panicf(0x89e180, 0x834df0, 0x8fead5, 0x2, 0xc0000c76b8, 0x1, 0x1, 0x8b62c0, 0x8cc040)
> 	C:/Users/scope/go/src/github.com/lighttiger2505/sqls/internal/handler/handler.go:52 +0x93
> github.com/lighttiger2505/sqls/internal/handler.(*Server).Handle.func1(0xc00008caf0, 0xc0000c7d98)
> 	C:/Users/scope/go/src/github.com/lighttiger2505/sqls/internal/handler/handler.go:63 +0xcb
> panic(0x89e180, 0x834df0)
> 	C:/hirano/001.InsDir/Go/src/runtime/panic.go:679 +0x1c0
> github.com/lighttiger2505/sqls/internal/completer.(*Completer).columnCandidates(0x0, 0xc000169580, 0xe, 0x10, 0x835720, 0x0, 0x0, 0x0)
> 	C:/Users/scope/go/src/github.com/lighttiger2505/sqls/internal/completer/completer.go:423 +0x93
> github.com/lighttiger2505/sqls/internal/completer.(*Completer).Complete(0x0, 0xc0002d8000, 0x5b96, 0xc000453fa0, 0x1f, 0x2, 0x10, 0x0, 0x0, 0x8, ...)
> 	C:/Users/scope/go/src/github.com/lighttiger2505/sqls/internal/completer/completer.go:237 +0x9af
> github.com/lighttiger2505/sqls/internal/handler.(*Server).handleTextDocumentCompletion(0xc0000803c0, 0x9857e0, 0xc00000a0c8, 0xc0000f6000, 0xc00008caf0, 0x16, 0x0, 0x0, 0x2)
> 	C:/Users/scope/go/src/github.com/lighttiger2505/sqls/internal/handler/completion.go:27 +0x171
> github.com/lighttiger2505/sqls/internal/handler.(*Server).handle(0xc0000803c0, 0x9857e0, 0xc00000a0c8, 0xc0000f6000, 0xc00008caf0, 0x0, 0xc000162240, 0x16, 0xa)
> 	C:/Users/scope/go/src/github.com/lighttiger2505/sqls/internal/handler/handler.go:90 +0x9c1
> github.com/lighttiger2505/sqls/internal/handler.(*Server).Handle(0xc0000803c0, 0x9857e0, 0xc00000a0c8, 0xc0000f6000, 0xc00008caf0, 0x0, 0x0, 0x0, 0x0)
> 	C:/Users/scope/go/src/github.com/lighttiger2505/sqls/internal/handler/handler.go:67 +0xd8
> github.com/sourcegraph/jsonrpc2.(*HandlerWithErrorConfigurer).Handle(0xc000036d30, 0x9857e0, 0xc00000a0c8, 0xc0000f6000, 0xc00008caf0)
> 	C:/Users/scope/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.0.0-20200429184054-15c2290dcb37/handler_with_error.go:21 +0x7a
> github.com/sourcegraph/jsonrpc2.(*Conn).readMessages(0xc0000f6000, 0x9857e0, 0xc00000a0c8)
> 	C:/Users/scope/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.0.0-20200429184054-15c2290dcb37/jsonrpc2.go:522 +0x571
> created by github.com/sourcegraph/jsonrpc2.NewConn
> 	C:/Users/scope/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.0.0-20200429184054-15c2290dcb37/jsonrpc2.go:334 +0x1e0

The connection information of .vimrc is as follows.
```vim
autocmd User lsp_setup call lsp#register_server({
\   'name': 'sqls',
\   'priority': 15,
\   'cmd': {server_info->['sqls']},
\   'whitelist': ['sql'],
\   'initialization_options': {
\   'sqls': {
\     'connections': [
\     {
\       'driver': 'postgresql',
\       'dataSourceName': 'host=LOCAL-IP port=5432 dbname=GTX1 user=postgres password=PASSWORD sslmode=disable',
\     },
\   ],}},
\ })
```
Thank you.

**Comment by lighttiger2505** [comment]
The error occurs because the database table and column information cannot be cached due to the inability to connect to the database. Please review the database settings.


The connection settings are incorrect. The following is correct. `workspace_config` is missing.

```vim　
autocmd User lsp_setup call lsp#register_server({
\   'name': 'sqls',
\   'cmd': {server_info->['sqls']},
\   'whitelist': ['sql'],
\   'workspace_config': {
\     'sqls': {
\       'connections': [
\         {
\           'driver': 'postgresql',
\           'dataSourceName': 'host=LOCAL-IP port=5432 dbname=GTX1 user=postgres password=PASSWORD sslmode=disable',
\         },
\       ],
\     },
\   },
\ })
```

**Comment by unikuragit** [comment]
I'm sorry, I overlooked it.
I tried again after changing the settings, but it was still an error.
sqls seems to die.
Only sqls is used for the LSP provider.

> 05/15/20 16:32:35:["s:on_stdout client option on_notification() error","Vim(call):E631: ch_sendraw(): write failed","function <SNR>294_out_cb[2]..<SNR>293_on_stdout[71]..<SNR>211_on_notification[17]..<SNR>211_handle_initialize[25]..<SNR>292_callback[1]..<SNR>292_next[9]..<lambda>16[1]..<SNR>211_ensure_conf[14]..<SNR>292_callback[1]..<SNR>292_next[9]..<lambda>17[1]..<SNR>211_ensure_open[25]..<SNR>211_send_notification[7]..lsp#client#send_notification[1]..<SNR>293_lsp_send[36]..async#job#send[1]..<SNR>294_job_send, line 6"]
> 05/15/20 16:32:35:["<---(stderr)",1,"sqls",["2020/05/15 16:32:35 sqls: reading on stdin, writing on stdout",""]]
> 05/15/20 16:32:35:["s:on_exit",1,"sqls","exited",1]
> 

I think the DB connection information is correct.
The location of the cause is not clear, but we will report it.

**Comment by unikuragit** [comment]
I solved my problem.
The cause was that the **PGCLIENTENCODING** environment variable was set to **'SJIS'** because of the encoding of the connection destination PostgreSQL.
It worked when I changed **PGCLIENTENCODING = 'UNICODE'**.
Thank you for your support.
