### ISSUE TITLE
Is it possible to see the type information for column in sqls?

### ISSUE THREAD

**Issue by sylba2050** [lighttiger2505/sqls#15]
Many language server can get document information such as variables and functions, so that I can check function arguments and variable type information.

Is the same possible with sqls?
I want to get colum type info and more...

**Comment by lighttiger2505** [comment]
@sylba2050 It is possible to add the features you request. However, RDBMS has dialects, and different ways to get help. Need a design to abstract the dialect differences.
I can't do that right away, but I have a hope to add that feature in the future.

**Comment by sylba2050** [comment]
Thank you for your reply！

I understand that it is difficult to implement, so I close this issue once.

Thanks
