### ISSUE TITLE
change lib/pq to jackc/pgx

### ISSUE THREAD

**Issue by Jackson-soft** [lighttiger2505/sqls#19]
![Screenshot_20200818_101501](https://user-images.githubusercontent.com/3928114/90464090-1df4e780-e13f-11ea-8a4b-13daace23951.png)

**Comment by lighttiger2505** [comment]
thanks for contribution.
It's not easy to apply pgx to sqls, which also supports databases other than postgresql, because pgx does not implement the database.sql interface.I will address this issue when my resources are available, but I can't do it quickly enough.

**Comment by Jackson-soft** [comment]
![image](https://user-images.githubusercontent.com/3928114/91936050-a9669f00-ed21-11ea-93a0-0c7cd742b7c9.png)
