### ISSUE TITLE
Support for the SELECT query with a new line immediately after `SELECT`

### ISSUE THREAD

**Issue by wakamenod** [lighttiger2505/sqls#21]
Hello, thanks for the great project.

One thing I noticed using sqls is that SELECT statement with the syntax like below does not return
the results:

```sql
SELECT
   select_list
FROM
   table_name;
```

It returns the number of rows affected.
Would be nice if this type of SELECT also be supported.

Thanks.

**Comment by lighttiger2505** [comment]
Thanks for contribution.

Hmm. I was unable to reproduce the bug you reported in my environment.

If you have the time. Could you please describe a more detailed reproduction procedure?
The following format is preferred.

```
**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
````

**Comment by wakamenod** [comment]
hi, thanks for your reply.

i will re-check the issue this weekend.
maybe this  is the problem at my client side. (i'm using it from emacs)

and sorry i  was a bit unclear about the way to reproduce. i will  use your  template.

thanks,

**Comment by wakamenod** [comment]
Sorry, my example query above was wrong.

**To Reproduce**

1. Run `Execute Query` command with the query below:

```
SELECT
*
FROM accounts;
```

Please note there is no space before `*`.

2. Check the result output. which is

```
Query OK, 7 row affected
```

**Expected behavior**
Returns the result rows:

```
+----------------------+---------+
|       PRC DATE       | PRC AMT |
+----------------------+---------+
| 2018-10-26T00:00:00Z |   12000 |
| 2018-10-28T00:00:00Z |    2500 |
| 2018-10-31T00:00:00Z |  -15000 |
| 2018-11-03T00:00:00Z |   34000 |
| 2018-11-04T00:00:00Z |   -5000 |
| 2018-11-06T00:00:00Z |    7200 |
| 2018-11-11T00:00:00Z |   11000 |
+----------------------+---------+
7 rows in set
```

**Versions**
OS: macOS 10.15.6
sqls: the latest at master

**Additional context**
I can get result if I put a space before the asterisk.

**Comment by wakamenod** [comment]
@lighttiger2505 
Thank you for your work.
i have confirmed it's fixed.
