### ISSUE TITLE
Please make a new release 

### ISSUE THREAD

**Issue by przepompownia** [lighttiger2505/sqls#29]
I am not familiar with golang and suspect that the version installed by `go get` still have a bug wiith completion quoted table names. Is that true?

Please additionally add a hint how to build master version of sqls.

**Comment by arp242** [comment]
`go get github.com/lighttiger2505` should get the latest version from the master branch, you typically want to use `go get -u` to update everything.

The source is stored in `~/go/src/github.com/lighttiger2505/sqls`, so you can check this directory if you want to be sure.

**Comment by przepompownia** [comment]
Indeed, this command seems to build up sqls from master. I would like to ensure I have the fresh version before reporting any bug. Note that I cannot still verify it by  using `--version`:
```
 $ ~/go/bin/sqls --version
sqls Version:, Revision:
```

**Comment by arp242** [comment]
The version is set by a compile-time flag: https://github.com/lighttiger2505/sqls/blob/master/Makefile#L7

So it's normal that it's empty when you build it from git.

**Comment by przepompownia** [comment]
OK, I see the version after build with `make` and (more important) I can build `sqls` directly from any branch. Thanks for all basic hints. 

Still, it would be nice to see the version regardless of how it's built.

**Comment by lighttiger2505** [comment]
@przepompownia I too feel that release version control will be needed. I'm hoping to sort it out in the near future.
