### ISSUE TITLE
Cannot complete columns if table name is quoted

### ISSUE THREAD

**Issue by przepompownia** [lighttiger2505/sqls#32]
Assume we have `order` and `logs` table, both with `id` column and query buffer
```sql
SELECT *
FROM `order` o
JOIN logs l
WHERE 
-- cursor here
```
and we want to see possible columns after `l`, `logs`, `o`, and `order`. Currently, I see only column list for `l` and `logs`. After quoting `logs` the server returns an empty completion list. 

sqls Version:v0.1.0, Revision:f955831, Debian sid, tested on MariaDB

**Comment by lighttiger2505** [comment]
Thinks for contribution. I was able to successfully reproduce the problem. This is a bug and will be fixed. Please wait a moment.

**Comment by lighttiger2505** [comment]
@przepompownia Fix completed.

**Comment by przepompownia** [comment]
```sql
SELECT * FROM `order` o WHERE o.-- cursor here
SELECT * FROM `order` o WHERE `order`.-- cursor here
```
There is still no results after triggering completion.
```
 $ ~/go/bin/sqls --version 
sqls Version:v0.1.0, Revision:cd0db6b
```

**Comment by lighttiger2505** [comment]
@przepompownia Sorry. My code fix was incomplete. Next time you should be healed.
https://github.com/lighttiger2505/sqls/pull/34

**Comment by przepompownia** [comment]
Column name completion was healed with #34 Thanks!
