### ISSUE TITLE
Where does the config go?

### ISSUE THREAD

**Issue by commandodev** [lighttiger2505/sqls#41]
**Describe the bug**
I'm trying to configure this package with spacemacs. I don't know what config file I need to create in order to create a connection.

**To Reproduce**
I've created `~/.config/sqls/config.yml` and `$PROJECT/.sqls/config.json`. Neither of these appear to be getting picked up from `sqls`

I've run

```
sqls -trace -config ./.sqls/config.json
sqls -trace -config ~/.config/sqls/config.yml
```

But can't see anything that might tell me what's going on.

**Expected behavior**
An error message telling me what files are trying to be read (or not being found). More explicit documentation to help me configure correctly

**Versions (please complete the following information):**
 - OS Version: ubuntu
 - sqls Version: Unstalled with `go get github.com/lighttiger2505/sqls` today (2021-01-24)
 
```
$ sqls -version
sqls Version:, Revision:
```

**Additional context**

**Comment by lighttiger2505** [comment]
There is an error in the way you are executing the command.

> ```
> sqls -trace -config ./.sqls/config.json
> sqls -trace -config ~/.config/sqls/config.yml
> ```

1. sqls does not interpret `~`.
2. sqls will not read files with relative paths

It may work if you do the following

```
sqls -config /home/lighttiger2505/.config/sqls/config.yml
sqls -config ${HOME}/.config/sqls/config.yml
```

**Comment by lighttiger2505** [comment]
There is also a way to output the log to a file using the log option. Posting the results of the log output will help you solve the problem.

```
sqls -log ${HOME}/sqls.log
```

**Comment by commandodev** [comment]
I've tried both of the variants you suggested (and the log file).

There's no extra output:

```
$ sqls -trace -config /home/ben/.config/sqls/config.yml -log /tmp/sqls.log
2021/01/26 10:13:10 db worker: start
2021/01/26 10:13:10 sqls: reading on stdin, writing on stdout
^C
$ cat /tmp/sqls.log 
2021/01/26 10:13:10 db worker: start
2021/01/26 10:13:10 sqls: reading on stdin, writing on stdout
```

Do you have an example of a yaml config file I could look at?

**Comment by lighttiger2505** [comment]
> Do you have an example of a yaml config file I could look at?

Sample settings are described in the README.
https://github.com/lighttiger2505/sqls#configuration-file-sample

**Comment by ruanwenjun** [comment]
> I've tried both of the variants you suggested (and the log file).
> 
> There's no extra output:
> 
> ```
> $ sqls -trace -config /home/ben/.config/sqls/config.yml -log /tmp/sqls.log
> 2021/01/26 10:13:10 db worker: start
> 2021/01/26 10:13:10 sqls: reading on stdin, writing on stdout
> ^C
> $ cat /tmp/sqls.log 
> 2021/01/26 10:13:10 db worker: start
> 2021/01/26 10:13:10 sqls: reading on stdin, writing on stdout
> ```
> 
> Do you have an example of a yaml config file I could look at?

I also meet this problem, I execute sqls at shell, but get no output.

**Comment by mattn** [comment]
sqls is run by client of language server protocol. It should not be run by shell.
