### ISSUE TITLE
Support MSSQL

### ISSUE THREAD

**Issue by Lenbok** [lighttiger2505/sqls#56]
**Describe the solution you'd like**
I've just started to use sqls and it is very nice. I would love to be able to use it for all the DBMS I encounter. Currently the main DBMS I am missing support for is MSSQL. Please add support for this.

**Describe alternatives you've considered**
Not using sqls.

**Additional context**
There appears to be a golang MSSQL driver that is actively developed at: https://github.com/denisenkom/go-mssqldb
It supports the database/sql package. 

For testing, you can run MSSQL via docker `FROM mcr.microsoft.com/mssql/server`

Do you have developer-level docs on what is involved in adding support for a new DBMS?

**Comment by christianfosli** [comment]
Nice to see this added :smile:

Just tried it out with Neovim 0.6. Code completion works great!

I also tried some of the code actions (i.e. Execute Query, Show Databases) but I get the error **method workspace/execute
Command is not supported by any of the servers registered for the current buffer**.

Does that sound like a configuration error on my side, or it's not supported for MSSQL yet?

**Comment by christianfosli** [comment]
Nevermind me, looks like I just forgot to set 
`client.resolved_capabilities.execute_command = true` in my neovim LSP configuration. [Ref sqls.nvim plugin docs](https://github.com/nanotee/sqls.nvim)
