### ISSUE TITLE
Server/client connection

### ISSUE THREAD

**Issue by jasminediaconu** [lighttiger2505/sqls#66]
Hi,

I would like to use the library with Monaco Editor and I was trying to understand how the client and server are communicating. However I cannot understand on which port is the server running? 
In the config files I could only find the database connection configs but nothing related to the client/server connection. 
I also checked out the sourcegraph/jsonrpc2 library and Gorilla WebSocket (which is used by jsonrpc2) but I still couldn't find anything useful. The only thing I can assume is that client and server are communicating through WebSockets. 

Maybe I am missing something, can I get some help on this?

**Comment by doncote** [comment]
@jasminediaconu did you end up figuring this out?
