### ISSUE TITLE
Per project connection

### ISSUE THREAD

**Issue by zer09** [lighttiger2505/sqls#91]
Is there way to setup per project connection, that will set the default database per project?

**Comment by zer09** [comment]
I was able to solve this using
```lua
require'lspconfig'.sqls.setup{
	cmd = { "sqls", "--config", vim.loop.cwd() .. "/sqls.yml" },
}
```

**Comment by milanglacier** [comment]
This is not a wise operation. As if current directory does not contain  `sqls.yml` the cmd will fail to run and we will receive an error.
A project local config should be highest prioritized.

**Comment by milanglacier** [comment]
I came up with a workaround in case the `config.yml` doesn't locate at `vim.loop.cwd()`, this is my nvim config:

```
require('lspconfig').sqls.setup {
    cmd = { require('bin_path').sqls },
    on_attach = function(client, bufnr)
        vim.cmd [[packadd! sqls.nvim]]

        on_attach(client, bufnr)
        require('sqls').on_attach(client, bufnr)
        local bufmap = vim.api.nvim_buf_set_keymap
        bufmap(bufnr, 'n', '<LocalLeader>ss', '<cmd>SqlsExecuteQuery<CR>', { silent = true })
        bufmap(bufnr, 'v', '<LocalLeader>ss', '<cmd>SqlsExecuteQuery<CR>', { silent = true })
    end,
    capabilities = capabilities,
    single_file_support = false,
    on_new_config = function(new_config, new_rootdir)
        new_config.cmd = {
            require('bin_path').sqls,
            '-config',
            new_rootdir .. '/config.yml',
        }
    end,
}
```

So we can make sure that the `config.yml` located at the root dir will be sent to the cmd that launch `sqls` lsp.

**Comment by vegerot** [comment]
It would be cool if sqls would look in the CWD for a `.sqls.yml`
