### ISSUE TITLE
Spawning language server with cmd failed

### ISSUE THREAD

**Issue by xllvrr** [lighttiger2505/sqls#96]
**Describe the bug**
When opening any .sql file, it automatically attempts to start the language server but produces an error message 
`"Spawning language server with cmd: `sqls` failed. The language server is either not installed, missing from PATH, or not executable"`

**To Reproduce**
1. Download and install sqls using `go install github.com/lighttiger2505/sqls@latest`
2. Setup the language server as below

> require'lspconfig'.sqls.setup{
>     on_attach = on_attach,
>     flags = {
>         debounce_text_changes = 150
>         },
>     cmd = {"sqls", "-config", "/home/xllvr/.config/sqls/config.yml"},
>     capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
> }

3. Open a .sql file

**Expected behavior**
Language server to spawn and begin functioning

**Versions (please complete the following information):**
 - OS Version: Arch Linux (Linux 5.16.15-arch1-1)
 - sqls Version: Latest

**Additional context**
Using cmp as the auto-completion, as well as having the native lsp setup (other language servers, namely R, tsserver and Pyright are functioning)

**Comment by vando026** [comment]
Did you put the go binary (`go install github.com/lighttiger2505/sqls@latest`) on your $PATH environment variable?

**Comment by xllvrr** [comment]
I did not but I've decided to use a separate program for SQL so it's fine. Thanks for the suggestion though. Forgot that this was still here
